version: '3.4'

services:
  test:
    image: test
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    command: npm run export.js -- /Users/mariadelmarvasquez/Desktop/config.xml

  redis:
    image: redis
    ports:
      - "6379:6379"
